name: flutter_zoom_drawer
description: A Flutter package with custom implementation of the Side Menu (Drawer)
version: 2.0.0
homepage: https://github.com/medyas/flutter_zoom_drawer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  vector_math: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
